---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-env
  template:
    metadata:
      labels:
        app: my-app-env
    spec:
      containers:
        - name: my-app-container-env
          image: my-app-image:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KE
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KE
            - name: IAMPORT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: iamport-access
                  key: IAMPORT_API_KEY
            - name: IAMPORY_SECRET
              valueFrom:
                secretKeyRef:
                  name: iampory-secret
                  key: IAMPORY_SECRET
